spring.application.name=blps-worker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.datasource.jndi-name=java:/PostgresDS
#spring.activemq.broker-url=tcp://helios.cs.ifmo.ru:61616?jms.prefetchPolicy.queuePrefetch=1
spring.jms.pub-sub-domain=false
spring.activemq.broker-url=tcp://localhost:61616?jms.prefetchPolicy.queuePrefetch=1
spring.activemq.user=admin
spring.activemq.password=admin
