spring.application.name=blps
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_db
spring.datasource.username=postgres3
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
