spring.application.name=blps
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_db
spring.datasource.username=postgres3
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
#users.file.path=/Users/danilasolodovnikov/itmo/sem6/blps/Labolatorn4Final/blps/data/users.xml
users.file.path=${jboss.server.data.dir}/blps/users.xml
camunda.bpm.client.base-url=http://localhost:8080/engine-rest
camunda.bpm.client.worker-id=blps-worker