app.assignment.transport=xmpp
app.xmpp.host=localhost
app.xmpp.port=5222
app.xmpp.domain=localhost
app.xmpp.sender.username=blps-sender
app.xmpp.sender.password=blps-sender
app.xmpp.gateway.username=blps-gateway
app.xmpp.gateway.password=blps-gateway
app.xmpp.gateway.jid=blps-gateway@localhost
