spring.application.name=blps
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_db
spring.datasource.username=postgres3
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.application.name=blps
#server.port=9081
#spring.datasource.url=jdbc:postgresql://localhost:5432/studs
#spring.datasource.username=s372411
#spring.datasource.password=mcurZKiA1A0W8lb1
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
