spring.application.name=blps
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery_db
spring.datasource.username=postgres3
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
users.file.path=/Users/danilasolodovnikov/itmo/sem6/blss/blps/blps/data/users.xml
